apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: cdnclusters.cluster.anevia.com
spec:
  group: cluster.anevia.com
  names:
    kind: CdnCluster
    plural: cdnclusters
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            role:
              type: string
          required:
          - role
          type: object
        status:
          properties:
            state:
              type: string
          type: object
      type: object
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
